name: F5XC Automation - AWS Instance Deployment

on:
  push:
    branches:
      - main

jobs:
  aws-instance-deployment:
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.tf-output.outputs.public_ip }}
      private_ip: ${{ steps.tf-output.outputs.private_ip }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: |
          cd aws_instance
          terraform init

      - name: Terraform Plan
        run: |
          cd aws_instance
          terraform plan

      - name: Terraform Apply
        run: |
          cd aws_instance
          terraform apply -auto-approve

      - name: Export Instance IPs
        id: tf-output
        run: |
          cd aws_instance
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
          echo "private_ip=$(terraform output -raw private_ip)" >> $GITHUB_OUTPUT

  f5xc-automation:
    runs-on: ubuntu-latest
    needs: aws-instance-deployment
    env:
      TF_VAR_public_ip: ${{ needs.aws-instance-deployment.outputs.public_ip }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Debug Files
        run: |
          cd f5-xc-lb
          ls -la
          grep -r "api_p12" .
      - name: Deploy F5XC HTTP only Load Balancer
        run: |
          cd f5-xc-lb
          echo "Running F5XC terraform Automation" 
          terraform init
          terraform apply -auto-approve
